### PR TITLE
BDE-207: concat html & js of elements

### PR DESCRIPTION
**Pull request by erne-mt**
reduces loading time by half (3.00-3.6s to around 1.7s)

as a byproduct of a possible solution for #2

### CODE REVIEW

**Comment by jtrs** [comment]
> reduces loading time by half 
> Tested locally or to base uploaded version?

**Comment by erne-mt** [comment]
Tested locally. But I do not have permissions for base upload.

But think about it, everytime the browser loads an element of the BDE there are two requests, one for the Polymer dom-module and one for the JS. This is possibly the reason for the longer loading time.

**Comment by jtrs** [comment]
I think, this is just a problem of locally development. The base uses already HTTP2, and therefore it is not really a problem anymore.

**Comment by hrbu** [comment]
Regaerding this issue just see http://stackoverflow.com/questions/38921856/optimal-way-to-package-web-components-assets-when-using-http2 and the first comment pointing to >> http://stackoverflow.com/questions/35588692/optimizing-file-cacheing-and-http2/36253257#36253257

**Pull request closed without merging**
